formatter: "markdown table"

sections:
  hide:
    - modules

content: |-
  ## Examples

  ```hcl
  {{ include "examples/basic/main.tf" -}}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
