name: Test module 
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**.tf'
      - '**.go'

jobs:
  check:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Run Go Tests
        working-directory: test
        run: go test -v -timeout 5m